version: '3.1'

services:

  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: monsuperpassroot
      MYSQL_DATABASE: groupomania
      MYSQL_USER: groupomania
      MYSQL_PASSWORD: groupomania
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: monsuperpassroot

  web:
    image: nginx
    volumes:
      - ./web/public/dist/groupomania:/usr/share/nginx/html
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
