version: '3.1'

services:

  db:
    image: mysql:8.0.23
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: monsuperpassroot
      MYSQL_DATABASE: groupomania
      MYSQL_USER: groupomania
      MYSQL_PASSWORD: groupomania
    volumes:
      - ./db_data/dev:/var/lib/mysql
    cap_add:
      - SYS_NICE

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: monsuperpassroot

  frontend-dev:
    image: node:15.3.0
    links:
      - db
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./web/client:/app
    command: npm start
    ports:
      - "4200:4200"

  backend-dev:
    image: node:15.3.0
    links:
      - db
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./web/server:/app
    command: npm run dev
    ports:
      - "8888:8888"
